### ISSUE TITLE
FR: use Apollo Client 3.x?

### ISSUE THREAD

**Issue by beatboxchad** [mirumee/saleor-sdk#64]
Recently I implemented a plugin for a client that changes the product price based on the `countryCode` GQL variable in the `ProductDetails` query. On the frontend, I was able to write a context provider and use the SDK `ProductDetails` query to use it.

However, the Apollo client caches GQL types no matter what query they come from. So for example, the custom price would get overwritten when fetching the Category when you view a product page. This is because the `ProductsList` does not support those variables.

I think the cleanest way to deal with this would be to use Apollo's per-type caching policy, but this is not available in v2.6. Would it be possible to move to Apollo 3.x?

If not, can you suggest another approach to this problem?

Thank you for this awesome software!

**Comment by jwm0** [comment]
Hey Chad, we have plans to migrate to Apollo v3 however I cannot comment on any timeline regarding this upgrade.

In regards to your question, right now it'd be wiser to move this mapper outside the SDK as it's still very much in heavy development and the internal APIs are subject to change without notice. If you insist on abstracting this logic internally you could create a new local field (`@client`) adjacent to the pricing field and use local resolvers to update it whenever the "real" pricing field changes. Note that the local resolvers are deprecated in Apollo v3 (though still working) so that might get out-of-date whenever we upgrade to v3.

**Comment by beatboxchad** [comment]
I really appreciate this! Thanks for your help, and again for the awesome software.
